language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0

before_script:
  - cd tests
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install --no-interaction

script: composer test

after_success:
  - cd ../; php tests/vendor/bin/coveralls  -c ./.coveralls.yml
